export const Tr = {
    "languageName": "Tr",
    "label": "Tr",
    "continueCourse": "Devam Et",
    "logout": "Çıkış",
    "languageTarget": "TÜRKÇE",
    "helperLanguageLabel": "Yardımcı Dil",
    "backButton": "← Geri",
    "unit": "Ünite",
    "topic": "Konu",
    "devPanel": "DEVELOPER PANEL",
    "devToolsTitle": "ZazaLingo Dev Tools",
    "devToolsSub": "İçerik yönetimi ve harita editörü",
    "testManagement": "Test & Soru Yönetimi",
    "testManagementDesc": "Testleri düzenle, yeni sorular ekle, konuları yönet",
    "mapEditor": "Harita Editörü",
    "mapEditorDesc": "İstasyonları taşı, ray kavislerini ayarla, etiketleri düzenle",
    "proverbs": "Atasözleri",
    "proverbsDesc": "Zazakî atasözlerini ve çevirilerini yönet, ekle, düzenle",
    "saveToServer": "Kodlara Kaydet (Dev Server)",
    "saveToServerDesc": "Tüm değişiklikleri anında kaynak dosyalara yazar. (Dev Server açık olmalıdır)",
    "exportJSON": "JSON Dışa Aktar",
    "exportJSONDesc": "Tüm veriyi JSON olarak dışa aktar ve kopyala",
    "resetProgress": "İlerlemeyi Sıfırla (Reset)",
    "resetProgressDesc": "Tren konumunu başlangıca döndürür ve bitirilen testleri temizler.",
    "saveSuccess": "Başarılı: Değişiklikler kaynak koddaki dosyalara kaydedildi!",
    "saveError": "Hata: Kaydedilemedi.",
    "connectionError": "Bağlantı Hatası: Dev Server çalışmıyor olabilir.",
    "resetConfirm": "Tüm ilerlemeniz silinecek. Emin misiniz?",
    "resetSuccess": "Başarılı: İlerleme sıfırlandı!",
    "deleteConfirm": "Bu öğeyi silmek istediğinize emin misiniz?",
    "jsonExportTitle": "JSON Dışa Aktarma",
    "copyToClipboard": "📋 Panoya Kopyala",
    "testQuestionManagement": "TEST & SORU YÖNETİMİ",
    "units": "📚 Üniteler",
    "station": "İstasyon",
    "noTests": "Test yok",
    "addTest": "+ Test Ekle",
    "addNewTopic": "+ Yeni Konu Ekle",
    "selectTestToEdit": "Düzenlemek için soldan bir test seçin",
    "moveTest": "↗ Testi Taşı",
    "delete": "🗑 Sil",
    "testTitle": "Test Başlığı",
    "questions": "Sorular",
    "questionTitle": "Soru Başlığı",
    "questionText": "Soru Metni",
    "options": "Seçenekler",
    "option": "Seçenek",
    "imageUrl": "Görsel URL",
    "addNewQuestion": "+ Yeni Soru Ekle",
    "newTestAdd": "Yeni Test Ekle",
    "testTitlePlaceholder": "Test başlığı...",
    "cancel": "İptal",
    "add": "Ekle",
    "moveTestWhere": "Testi Nereye Taşıyalım?",
    "rename": "İsimlendir",
    "ZzName": "Zazaca İsim",
    "ZzNamePlaceholder": "Zazaca isim...",
    "TrName": "Türkçe İsim",
    "TrNamePlaceholder": "Türkçe isim...",
    "EnName": "İngilizce İsim",
    "EnNamePlaceholder": "İngilizce isim...",
    "KrName": "Kurmancî İsim",
    "KrNamePlaceholder": "Kurmancî isim...",
    "save": "Kaydet",
    "unitRename": "Ünite İsimlendir",
    "ZzUnitName": "Zazaca Ünite İsmi",
    "ZzUnitNamePlaceholder": "Zazaca ünite ismi...",
    "TrUnitName": "Türkçe Ünite İsmi",
    "TrUnitNamePlaceholder": "Türkçe ünite ismi...",
    "EnUnitName": "İngilizce Ünite İsmi",
    "EnUnitNamePlaceholder": "İngilizce ünite ismi...",
    "KrUnitName": "Kurmancî Ünite İsmi",
    "KrUnitNamePlaceholder": "Kurmancî ünite ismi...",
    "unnamedTest": "İsimsiz Test",
    "proverbsTitle": "ATASÖZLERİ",
    "addButton": "+ Ekle",
    "noProverbsYet": "Henüz atasözü eklenmemiş",
    "noProverbsDesc": "Yukarıdaki \"+ Ekle\" butonuyla Zazaca atasözleri ve çevirilerini ekleyebilirsiniz.",
    "editProverb": "Atasözü Düzenle",
    "addNewProverb": "Yeni Atasözü Ekle",
    "ZzProverb": "Zazakî Atasözü *",
    "ZzProverbPlaceholder": "Zazaca atasözü yazın...",
    "TrTranslation": "Türkçe Karşılığı",
    "TrTranslationPlaceholder": "Türkçe çeviri...",
    "EnTranslation": "English Translation",
    "EnTranslationPlaceholder": "English translation...",
    "KrTranslation": "Kurmancî Werger",
    "KrTranslationPlaceholder": "Kurmancî werger...",
    "update": "Güncelle",
    "deleteProverbConfirm": "Bu atasözünü silmek istediğinize emin misiniz?",
    "tagWidth": "Etiket Genişliği",
    "settings": "Ayarlar",
    "musicSection": "Müzik",
    "enableMusic": "Müziği Kapat",
    "bgVolumeLabel": "Genel Müzik Ses Seviyesi",
    "testVolumeLabel": "Test Sırasındaki Müzik Seviyesi",
    "contributorsSection": "Katkıda Bulunanlar",
    "back": "Geri"
};
